import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "HRT Services by State | Hormone Replacement Therapy in LA, FL, AL, MS, TX, ID, UT, OK",
  description:
    "Comprehensive hormone replacement therapy (HRT) services for trans and gender divergent people in Louisiana, Florida, Alabama, Mississippi, Texas, Idaho, Utah, and Oklahoma. Licensed providers offering estrogen therapy, testosterone therapy, and customized HRT regimens through telemedicine.",
  keywords: [
    "HRT Louisiana",
    "HRT Florida",
    "HRT Alabama",
    "HRT Mississippi",
    "HRT Texas",
    "HRT Idaho",
    "HRT Utah",
    "HRT Oklahoma",
    "hormone replacement therapy Louisiana",
    "hormone replacement therapy Florida",
    "hormone replacement therapy Alabama",
    "hormone replacement therapy Mississippi",
    "hormone replacement therapy Texas",
    "hormone replacement therapy Idaho",
    "hormone replacement therapy Utah",
    "hormone replacement therapy Oklahoma",
    "transgender healthcare Louisiana",
    "transgender healthcare Florida",
    "transgender healthcare Alabama",
    "transgender healthcare Mississippi",
    "transgender healthcare Texas",
    "transgender healthcare Idaho",
    "transgender healthcare Utah",
    "transgender healthcare Oklahoma",
    "estrogen therapy",
    "testosterone therapy",
    "HRT telemedicine",
    "transgender HRT",
    "gender affirming care",
    "HRT New Orleans",
    "HRT Miami",
    "HRT Birmingham",
    "HRT Jackson MS",
    "HRT Houston",
    "HRT Dallas",
    "HRT Austin",
    "HRT Boise",
    "HRT Salt Lake City",
    "HRT Oklahoma City",
    "HRT Tulsa",
  ],
  openGraph: {
    title: "HRT Services by State | Hormone Replacement Therapy",
    description:
      "Comprehensive HRT services for trans and gender divergent people in Louisiana, Florida, Alabama, Mississippi, Texas, Idaho, Utah, and Oklahoma.",
    type: "website",
    url: "https://transnationalhealth.org/services-by-state",
  },
  alternates: {
    canonical: "https://transnationalhealth.org/services-by-state",
  },
}
