import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "HRT Services by State | Hormone Replacement Therapy in AL, AR, ID, IN, LA, MO, MT, ND, OK, SD, WV",
  description:
    "Comprehensive hormone replacement therapy (HRT) services for trans and gender divergent people in Alabama, Arkansas, Idaho, Indiana, Louisiana, Missouri, Montana, North Dakota, Oklahoma, South Dakota, and West Virginia. Licensed providers offering estrogen therapy, testosterone therapy, and customized HRT regimens through telemedicine.",
  keywords: [
    "HRT Alabama",
    "HRT Arkansas",
    "HRT Idaho",
    "HRT Indiana",
    "HRT Louisiana",
    "HRT Missouri",
    "HRT Montana",
    "HRT North Dakota",
    "HRT Oklahoma",
    "HRT South Dakota",
    "HRT West Virginia",
    "hormone replacement therapy Alabama",
    "hormone replacement therapy Arkansas",
    "hormone replacement therapy Idaho",
    "hormone replacement therapy Indiana",
    "hormone replacement therapy Louisiana",
    "hormone replacement therapy Missouri",
    "hormone replacement therapy Montana",
    "hormone replacement therapy North Dakota",
    "hormone replacement therapy Oklahoma",
    "hormone replacement therapy South Dakota",
    "hormone replacement therapy West Virginia",
    "transgender healthcare Alabama",
    "transgender healthcare Arkansas",
    "transgender healthcare Idaho",
    "transgender healthcare Indiana",
    "transgender healthcare Louisiana",
    "transgender healthcare Missouri",
    "transgender healthcare Montana",
    "transgender healthcare North Dakota",
    "transgender healthcare Oklahoma",
    "transgender healthcare South Dakota",
    "transgender healthcare West Virginia",
    "estrogen therapy",
    "testosterone therapy",
    "HRT telemedicine",
    "transgender HRT",
    "gender affirming care",
    "HRT Birmingham",
    "HRT Little Rock",
    "HRT Boise",
    "HRT Indianapolis",
    "HRT New Orleans",
    "HRT Kansas City",
    "HRT St. Louis",
    "HRT Billings",
    "HRT Fargo",
    "HRT Oklahoma City",
    "HRT Tulsa",
    "HRT Sioux Falls",
    "HRT Charleston WV",
  ],
  openGraph: {
    title: "HRT Services by State | Hormone Replacement Therapy",
    description:
      "Comprehensive HRT services for trans and gender divergent people in Alabama, Arkansas, Idaho, Indiana, Louisiana, Missouri, Montana, North Dakota, Oklahoma, South Dakota, and West Virginia.",
    type: "website",
    url: "https://transnationalhealth.org/services-by-state",
  },
  alternates: {
    canonical: "https://transnationalhealth.org/services-by-state",
  },
}
