import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Testosterone Replacement Therapy | TRT for Low Testosterone",
  description:
    "Professional testosterone replacement therapy (TRT) for men in Alabama, Arkansas, Idaho, Indiana, Louisiana, Missouri, Montana, North Dakota, Oklahoma, South Dakota, and West Virginia. Licensed providers offering hormone therapy for low T, fatigue, muscle loss, and testosterone deficiency. Call 844-HRTMEDS.",
  keywords: [
    "testosterone replacement therapy",
    "TRT",
    "low testosterone treatment",
    "low T therapy",
    "testosterone therapy for men",
    "male hormone replacement",
    "testosterone deficiency treatment",
    "TRT clinic",
    "testosterone optimization",
    "male hormone therapy",
    "TRT Alabama",
    "TRT Arkansas",
    "TRT Idaho",
    "TRT Indiana",
    "TRT Louisiana",
    "TRT Missouri",
    "TRT Montana",
    "TRT North Dakota",
    "TRT Oklahoma",
    "TRT South Dakota",
    "TRT West Virginia",
    "testosterone therapy Alabama",
    "testosterone therapy Arkansas",
    "testosterone therapy Idaho",
    "testosterone therapy Indiana",
    "testosterone therapy Louisiana",
    "testosterone therapy Missouri",
    "testosterone therapy Montana",
    "testosterone therapy North Dakota",
    "testosterone therapy Oklahoma",
    "testosterone therapy South Dakota",
    "testosterone therapy West Virginia",
  ],
  openGraph: {
    title: "Testosterone Replacement Therapy | Expert TRT Services",
    description:
      "Professional testosterone replacement therapy for men experiencing low T, fatigue, and decreased vitality. Licensed healthcare providers offering personalized hormone optimization.",
    type: "website",
  },
  alternates: {
    canonical: "https://transnationalhealth.org/testosterone-therapy",
  },
}
